name: neurotrace
description: "NeuroTrace — cyberpunk memory puzzle game"
publish_to: "none" # since this is not being published to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons for iOS-style icons (optional but useful)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/bg_texture.png