name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'        # use your stable version
          channel: 'stable'
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      # 👇 Generate app icons from assets/logo.png before building
      - name: Generate launcher icons
        run: flutter pub run flutter_launcher_icons:main

      # (Optional) make gradlew executable
      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: neurotrace-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
