name: Build NeuroTrace APK (Debug)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      # If your repo does NOT contain /android (e.g., web-only at first), 
      # uncomment this step to scaffold Android. Otherwise leave it out.
      # - name: Ensure Android scaffolding exists
      #   run: |
      #     if [ ! -d "android" ]; then
      #       flutter create --platforms android .
      #     fi

      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: neurotrace-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk