name: Build Android APKs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Generate launcher icons
        run: flutter pub run flutter_launcher_icons:main

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      # ---------------- AUTO-BUMP VERSION ----------------
      - name: Bump build number
        id: bump
        run: |
          CURRENT=$(grep '^version:' pubspec.yaml | sed 's/version: //')
          VERSION_NAME=$(echo $CURRENT | cut -d+ -f1)
          BUILD_NUMBER=$(echo $CURRENT | cut -d+ -f2)
          NEW_BUILD=$((BUILD_NUMBER+1))
          echo "New version: $VERSION_NAME+$NEW_BUILD"
          sed -i "s/^version: .*/version: $VERSION_NAME+$NEW_BUILD/" pubspec.yaml

      # ---------------- DEBUG BUILD ----------------
      - name: Build Debug APK
        run: flutter build apk --debug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: neurotrace-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      # ---------------- RELEASE BUILD ----------------
      - name: Build Release APK
        run: flutter build apk --release

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: neurotrace-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk