name: Build NeuroTrace APK (Debug)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable        # don't set flutter-version alongside channel
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Ensure Android scaffolding exists
        shell: bash
        run: |
          if [ ! -f android/app/src/main/AndroidManifest.xml ]; then
            echo "Android scaffolding missing — creating it..."
            flutter create . --platforms=android
          else
            echo "Android scaffolding already present."
          fi

      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: NeuroTrace-debug-${{ github.sha }}
          path: build/app/outputs/flutter-apk/app-debug.apk