name: Build NeuroTrace APK (Debug)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      # 🔧 Generate missing Android Gradle project (safe to run every build)
      - name: Create Flutter project scaffolding (Android only)
        run: flutter create . --platforms=android

      # (optional) Generate Android launcher icons if config exists
      - name: Generate launcher icons (Android)
        run: |
          if grep -q "flutter_launcher_icons:" pubspec.yaml; then
            flutter pub run flutter_launcher_icons
          else
            echo "flutter_launcher_icons not configured; skipping."
          fi

      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: NeuroTrace-debug
          path: build/app/outputs/flutter-apk/app-debug.apk