name: Build NeuroTrace APK (Debug)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "README.md"
      - ".github/ISSUE_TEMPLATE/**"
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    env:
      FLUTTER_CHANNEL: stable
      JAVA_VERSION: "17"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---- Java & Flutter ----------------------------------------------------
      - name: Setup Java (JDK ${{ env.JAVA_VERSION }})
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Flutter (${{ env.FLUTTER_CHANNEL }})
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true

      # ---- Caches ------------------------------------------------------------
      - name: Pub cache
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # ---- Get deps & sanity checks -----------------------------------------
      - name: Flutter pub get
        run: flutter pub get

      # Optional, uncomment if you want static analysis to fail the build
      # - name: Flutter analyze
      #   run: flutter analyze

      # ---- Build APK ---------------------------------------------------------
      - name: Build APK (debug)
        run: flutter build apk --debug

      # ---- Upload artifact ---------------------------------------------------
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: neurotrace-debug-${{ github.sha }}
          path: build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: error